# Generated by Django 5.2.3 on 2025-06-11 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("created_date", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_title", models.TextField()),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("title", "Title"),
                            ("raw_content", "Raw Content"),
                            ("image", "Image"),
                            ("footer", "Footer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("image", models.ImageField(upload_to="images/blog_pictures")),
                ("alt_text", models.TextField()),
                ("order", models.IntegerField()),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="blog.post",
                    ),
                ),
            ],
        ),
    ]
