# Generated by Django 5.2.3 on 2025-06-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="alt_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="section",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="section",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/blog_pictures"
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="section_title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
