# Generated by Django 5.2.3 on 2025-06-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_post_description_post_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/blog_thumbnails"
            ),
        ),
    ]
