# Generated by Django 5.2.3 on 2025-06-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_post_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="url",
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
